// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXPWGiiQafmbde06RYkGK3DgmZwzgZcaM',
    appId: '1:16468871445:web:ebcfb8f6d5fe211262011c',
    messagingSenderId: '16468871445',
    projectId: 'hemocentro-40c12',
    authDomain: 'hemocentro-40c12.firebaseapp.com',
    databaseURL: 'https://hemocentro-40c12-default-rtdb.firebaseio.com',
    storageBucket: 'hemocentro-40c12.appspot.com',
    measurementId: 'G-FKD1PNZQWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQQYsgE6RZYQwjdJtNJGQosgE32HINS8M',
    appId: '1:16468871445:android:6b83246dd72ebbf562011c',
    messagingSenderId: '16468871445',
    projectId: 'hemocentro-40c12',
    databaseURL: 'https://hemocentro-40c12-default-rtdb.firebaseio.com',
    storageBucket: 'hemocentro-40c12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyEVxVJIZMFiFTNK2Vm4nHuTAqG5FMM9s',
    appId: '1:16468871445:ios:255109d083722c4b62011c',
    messagingSenderId: '16468871445',
    projectId: 'hemocentro-40c12',
    databaseURL: 'https://hemocentro-40c12-default-rtdb.firebaseio.com',
    storageBucket: 'hemocentro-40c12.appspot.com',
    iosClientId: '16468871445-346kod2f1n8e7vtd23gimu5dllvp5ihh.apps.googleusercontent.com',
    iosBundleId: 'com.example.hemocentro1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyEVxVJIZMFiFTNK2Vm4nHuTAqG5FMM9s',
    appId: '1:16468871445:ios:255109d083722c4b62011c',
    messagingSenderId: '16468871445',
    projectId: 'hemocentro-40c12',
    databaseURL: 'https://hemocentro-40c12-default-rtdb.firebaseio.com',
    storageBucket: 'hemocentro-40c12.appspot.com',
    iosClientId: '16468871445-346kod2f1n8e7vtd23gimu5dllvp5ihh.apps.googleusercontent.com',
    iosBundleId: 'com.example.hemocentro1',
  );
}
